name: Template Improvement
description: Suggest an improvement to the Arche template system with implementation details
title: "[Improvement]: "
labels: ["improvement", "status:proposed"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for proposing an improvement!
        
        This template helps capture improvements with enough detail for automated implementation.
        
        **Types of improvements:**
        - Improvements to existing modes/forms
        - New features or better patterns
        - Documentation and discoverability
        - **New mode proposals** (when real-world patterns emerge)
        
        **How this works:**
        1. You submit this issue with implementation details
        2. Issue is automatically labeled by category/priority
        3. Arche maintainer reviews and adds `status:approved` label
        4. GitHub Actions automatically creates a PR with your changes
        5. Maintainer reviews and merges the PR
        
        **You do not need write access to the repository**—just the ability to create issues.

  - type: input
    id: title
    attributes:
      label: Improvement Title
      description: One-line description of the improvement
      placeholder: "Add Python version validation to init_env.md"
    validations:
      required: true

  - type: dropdown
    id: mode
    attributes:
      label: Mode
      description: Which mode does this improvement target?
      options:
        - "✅ 3-layer (Mature)"
        - "🚀 agentic-swarm (Emerging)"
        - "🚀 event-driven (Emerging)"
        - "🚀 rl-loop (Emerging)"
        - "🌱 New mode proposal"
        - "📊 Mode status update (maturity level change)"
        - "🔧 Cross-mode / Framework-wide"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: Which part of the system does this improve?
      options:
        - Mode Architecture
        - Form/Template within Mode
        - Bootstrap Script
        - Documentation Quality
        - SEO & Discoverability
        - Marketing & Outreach
        - Social Media
        - Community Growth
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What issue does this solve? What learning prompted this?
      placeholder: |
        During environment setup, we encountered...
        This caused confusion because...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: High-level description of what should change
      placeholder: |
        Add a validation step that checks Python version...
        Update the directive to include...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation (Code Diffs)
      description: Provide diffs for files that need changes. Use code blocks with diff syntax.
      placeholder: |
        #### `template/_shared/agents.md`
        ```diff
        - Old text that should be removed
        + New text that should be added
        ```
        
        #### `template/automation/requirements.txt`
        ```diff
        + pandas>=2.1.0
        ```
      render: markdown

  - type: textarea
    id: commit_message
    attributes:
      label: Suggested Commit Message
      description: Follow conventional commits format (feat:, fix:, docs:, etc.)
      placeholder: |
        feat: Add Python version validation to init_env.md
        
        - Add venv detection step in section 7
        - Include version checking with clear error messages
        - Update troubleshooting section with common issues
        
        Closes #XX
      render: markdown

  - type: textarea
    id: testing
    attributes:
      label: Testing Steps
      description: How to verify this improvement works
      placeholder: |
        - [ ] Bootstrap new automation project
        - [ ] Verify Python version is checked
        - [ ] Test with Python 3.9 (should warn)
        - [ ] Test with Python 3.12 (should succeed)
      render: markdown

  - type: textarea
    id: related
    attributes:
      label: Related Issues
      description: Link to related issues or discussions
      placeholder: |
        - Related to #123
        - Fixes #456
        - See discussion #789

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information (error messages, examples, screenshots)
      placeholder: |
        Error encountered:
        ```
        ImportError: No module named 'pandas'
        ```

  - type: markdown
    attributes:
      value: |
        ---
        
        ## Optional: Anonymous Telemetry
        
        The following fields help us understand arche usage patterns to prioritize improvements and track mode maturity. **All fields are optional** and contain no identifying information.
        
        See [TELEMETRY.md](https://github.com/coreyshort/arche/blob/main/TELEMETRY.md) for details.

  - type: dropdown
    id: project_type
    attributes:
      label: Project Type (Optional)
      description: What kind of project are you building?
      options:
        - "Internal tool / automation"
        - "SaaS / commercial product"
        - "Open source project"
        - "Research / academic"
        - "Personal / learning"
        - "Enterprise application"
        - "Other"
        - "Prefer not to say"
    validations:
      required: false

  - type: dropdown
    id: team_size
    attributes:
      label: Team Size (Optional)
      description: How many people work on this project?
      options:
        - "Solo (1)"
        - "Small (2-3)"
        - "Medium (4-10)"
        - "Large (10+)"
        - "Prefer not to say"
    validations:
      required: false

  - type: input
    id: arche_version
    attributes:
      label: Arche Version (Optional)
      description: If known, which version of arche are you using?
      placeholder: "1.0.0 or commit hash"
    validations:
      required: false
